### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-rboris2000#1]
When attempting to access this at https://githubschool.github.io/github-games-rboris2000, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @rboris2000?

**Comment by rboris2000** [comment]
Hello Matt,
I do not understand this. What exactly needs to be done and in which repo? 
------- Sincerely, Boris Rovner 

    On Wednesday, May 22, 2019, 8:51:58 a.m. EDT, GitHub Teacher <notifications@github.com> wrote:  
 
 
When attempting to access this at https://githubschool.github.io/github-games-rboris2000, I am getting a 404. This could be caused by a couple things:
   
   - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
   - the index.html file is incorrectly named inde.html. We will fix this together in class.

Can you please fix the first bullet @rboris2000?

**Comment by rboris2000** [comment]
the issue is fixed.
